# Generated by Django 3.2.5 on 2021-10-31 20:48

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('min_cost', models.FloatField()),
                ('color', colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FF0000', 'red')], default='#FFFFFF', max_length=18)),
                ('about', models.TextField()),
                ('internal_possibility', models.TextField()),
                ('appearance', models.TextField()),
                ('internal_photo', models.ImageField(upload_to='')),
                ('external_photo', models.ImageField(upload_to='')),
                ('side_photo', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PositionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('engine', models.CharField(max_length=255)),
                ('fuel', models.CharField(max_length=255)),
                ('available_volume', models.CharField(max_length=255)),
                ('drive_type', models.CharField(max_length=255)),
                ('transmission_box', models.CharField(max_length=255)),
                ('overclocking_time', models.FloatField()),
                ('max_speed', models.IntegerField()),
                ('lockingRearWheelDifferential', models.BooleanField(default=False)),
                ('automaticAutoHold', models.BooleanField(default=False)),
                ('childSeatLock', models.BooleanField(default=False)),
                ('led_headlight', models.CharField(max_length=255)),
                ('full_weight', models.FloatField()),
                ('empty_weight', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('seats_count', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobile.car')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
