# Generated by Django 3.2.5 on 2021-11-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
