# Generated by Django 3.2.5 on 2021-11-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0002_car_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='positioncategory',
            name='cost',
            field=models.FloatField(default=250000000),
        ),
    ]
