# Generated by Django 3.2.5 on 2021-11-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0003_positioncategory_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positioncategory',
            name='cost',
            field=models.FloatField(),
        ),
    ]
