# Generated by Django 3.2.5 on 2021-11-01 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0004_alter_positioncategory_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='min_cost',
            new_name='cost_from',
        ),
    ]
