# Generated by Django 3.2.5 on 2022-08-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='groups',
            field=models.ManyToManyField(related_name='roles', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, through='users.UserRole', to='users.Role'),
        ),
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
