"""
Django testing settings for rhythm project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/

export DJANGO_SETTINGS_MODULE=rhythm.settings_test
"""

from .settings import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(ex%$t037)pyxzt$2^v=q#dtqln*cyvff^w96h8b!@gv)yx_*%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ENV = 'testing'

ALLOWED_HOSTS = ['localhost']

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DATABASE_NAME', 'test'),
        'USER': 'test',
        'PASSWORD': 'test',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'
EMAIL_FROM = 'info@localhost'
